import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Sidebar from "@/widgets/Sidebar/ui/Sidebar";
import classNames from "classnames";
import Navbar from "@/widgets/Navbar/ui/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Sidebar/>
        <Navbar/>
        <div className={classNames('ps-60 bg-amber-100 h-screen pt-14')}>
            <div>
                {children}
            </div>
        </div>
        </body>
        </html>
    )
}
